### ISSUE TITLE
Add LineSpace() for \addlinespace command

### ISSUE THREAD

**Issue by ki-chi** [tpapp/LaTeXTabulars.jl#17]
The `\addlinespace[<wd>]` command in the `booktabs` package is quite useful like `\toprule` and `\cmidrule`. I can see how introducing the command as `LineSpace([wd])` to this package would make it even more appealing.

Like that:
```
latex_tabular("/tmp/table.tex",
              Tabular("lcl"),
              [Rule(:top),
               [L"\alpha", L"\beta", "sum"],
               Rule(:mid),
               [1, 2, 3],
               LineSpace(),  # convert to "\addlinespace"
               [4, 5, 6],
               Rule(:bottom)])
```

**Comment by tpapp** [comment]
Closed by #18, thanks @ki-chi!
